#!/usr/bin/env python3

"""CSV clean-up tool
"""

import os
import sys
import argparse
import subprocess

pathSublimeText = 
pathCSVs = 


try:
	subprocess.call([path_to_notepad, path_to_file])
catch:
	print("Process call failed.")